[package]
name = "fatty_acid_macro"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.39"
syn = { version = "2.0.99", features = ["full"] }

[dev-dependencies]
trybuild = "1.0.103"
